version: '3.8'

services:
  ctf-lab:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=ctf-lab-super-secret-key-2024
    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
    restart: unless-stopped
    networks:
      - ctf-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ctf-lab
    networks:
      - ctf-network
    restart: unless-stopped

networks:
  ctf-network:
    driver: bridge
